# Generated by Django 5.2.17 on 2026-10-06 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('EntrepriseApp', '0002_alter_entreprise_type_entreprise_utilisateur_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expedition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50, unique=True)),
                ('ville_depart', models.CharField(max_length=100)),
                ('ville_arrivee', models.CharField(max_length=100)),
                ('poids_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_souhaitee', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('publiee', 'Publiee'), ('attribuee', 'Attribuee'), ('en_cours', 'En cours'), ('livree', 'Livree'), ('annulee', 'Annulee')], default='publiee', max_length=20, verbose_name='Statut')),
                ('entreprise_chargeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expeditions', to='EntrepriseApp.entreprise')),
            ],
        ),
    ]
