# Generated by Django 5.2.17 on 2026-10-06 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExpeditionApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expedition',
            name='reference',
            field=models.CharField(blank=True, editable=False, max_length=50, unique=True),
        ),
    ]
