# Generated by Django 5.2.17 on 2026-10-06 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('EntrepriseApp', '0002_alter_entreprise_type_entreprise_utilisateur_and_more'),
        ('ExpeditionApp', '0002_alter_expedition_reference'),
        ('VehiculeApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delai', models.CharField(max_length=100)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('acceptee', 'Acceptee'), ('refusee', 'Refusee')], default='en_attente', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expedition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offres', to='ExpeditionApp.expedition')),
                ('transporteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offres', to='EntrepriseApp.entreprise')),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offres', to='VehiculeApp.vehicule')),
            ],
        ),
    ]
