# Generated by Django 5.2.17 on 2026-10-06 10:40

import EntrepriseApp.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EntrepriseApp', '0002_alter_entreprise_type_entreprise_utilisateur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entreprise',
            name='adresse',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(20, message="L'adresse doit contenir au moins 20 caractères"), django.core.validators.MaxLengthValidator(300, message="L'adresse ne peut pas dépasser 300 caractères")]),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='raison_sociale',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Format Incorrect -(ex, 1234567AAM000 ou 1234567-A-A-M-000).', regex='^\\d{7}[/ -]?[A-Za-z][/ -]?[ABDNPEabdnpe][/ -]?[MPCNEmpcne][/ -]?\\d{3}$')]),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[EntrepriseApp.models.validate_email]),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('chargeur', 'Chargeur'), ('transporteur', 'Transporteur')], max_length=20),
        ),
    ]
