# Generated by Django 5.2.17 on 2026-10-06 10:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VehiculeApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicule',
            name='capacite_kg',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(100, message="La capacité doit être d'au moins 100 kg")]),
        ),
    ]
